# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderun', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='body',
        ),
        migrations.AddField(
            model_name='code',
            name='email',
            field=models.CharField(default='yourcode@example.com', max_length=140),
        ),
        migrations.AddField(
            model_name='code',
            name='file',
            field=models.FileField(default='NULL', upload_to=''),
        ),
    ]
